name: Lighthouse CI

on: [workflow_dispatch]

jobs:
  lighthouse:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '18.17.0'

    - name: Install dependencies
      run: yarn install

    - name: Build Next.js Application
      run: yarn build

    - name: Start Next.js Server
      run: yarn start &
      env:
        PORT: 3000

    - name: Run Lighthouse CI
      uses: treosh/lighthouse-ci-action@v2
      with:
        configPath: "./lighthouserc.json"
        temporaryPublicStorage: true

    - name: Upload Lighthouse Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: lighthouse-reports
        path: '.lighthouseci'

    # Optionally, you can add steps to comment on PR with Lighthouse scores
    # - name: Comment Lighthouse Report on PR
    #   ... 