name: Trigger Lighthouse CI

on:
  workflow_dispatch:
    inputs:
      node-version:
        description: 'Node.js version'
        default: '21'
        required: false
        type: string
      build-script:
        description: 'Build script command'
        default: 'yarn run build'
        required: false
        type: string
      lighthouse-config-path:
        description: 'Path to the Lighthouse configuration file'
        default: './lighthouse/lighthouserc.yml'
        required: false
        type: string

jobs:
  lighthouse-ci-audit:
    name: 🌟 Lighthouse CI Audit
    uses: dpbeaumont/ligthouse-ci/.github/workflows/lighthouse-ci.yml@main
    with:
      node-version: ${{ github.event.inputs.node-version }}
      build-script: ${{ github.event.inputs.build-script }}
      lighthouse-config-path: ${{ github.event.inputs.lighthouse-config-path }}
