name: Lighthouse CI

on: [workflow_dispatch]

jobs:
  lighthouse:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '18.17.0'

    - name: yarn install, build
      run: |
          yarn install
          yarn run build

    - name: run Lighthouse CI
      id: lighthouse
      run: |
          npm install -g @lhci/cli@0.13.x
          lhci autorun \
          --config=./lighthouserc.json
      env:
            LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
    
    - name: Job successful feedback
      if: ${{ success() }}
      run: |
              echo "Triggered by **${{ github.actor	}}** ∙ deployed from **${{ github.ref_name	}}**" >> $GITHUB_STEP_SUMMARY
              echo ' ' >> $GITHUB_STEP_SUMMARY
              echo "**Lighthouse results:**" >> $GITHUB_STEP_SUMMARY
              echo "Performance: ${{ fromJSON(steps.lighthouse.outputs.manifest)[0].summary.performance }}" >> $GITHUB_STEP_SUMMARY
              echo "Accessibility: ${{ fromJSON(steps.lighthouse.outputs.manifest)[0].summary.accessibility }}" >> $GITHUB_STEP_SUMMARY
              echo "Best-practices: ${{ fromJSON(steps.lighthouse.outputs.manifest)[0].summary.best-practices }}" >> $GITHUB_STEP_SUMMARY
              echo "SEO: ${{ fromJSON(steps.lighthouse.outputs.manifest)[0].summary.seo }}" >> $GITHUB_STEP_SUMMARY
              echo "PWA: ${{ fromJSON(steps.lighthouse.outputs.manifest)[0].summary.pwa }}" >> $GITHUB_STEP_SUMMARY
              echo ' ' >> $GITHUB_STEP_SUMMARY
