name: Lighthouse CI
on: [workflow_dispatch, pull_request]

jobs:
  lighthouse-ci-audit:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4

    - name: yarn install, build
      run: |
          yarn install
          yarn run build

    - name: Run Lighthouse CI
      run: |
        npm install -g @lhci/cli@0.13.x
        lhci autorun --config=./lighthouse/lighthouserc.yml
        
    - name: Convert JSON to Markdown and Add to Job Summary
      run: |
        node ./lighthouse/lighthouseResultsToMarkdown.js >> $GITHUB_STEP_SUMMARY

    - name: Archive Lighthouse Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: lighthouse-results
        path: lighthouseci/*
