name: Lighthouse CI

on: [workflow_dispatch]

jobs:
  lighthouse:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.17.0'

    - name: yarn install, build
      run: |
          yarn install
          yarn run build

    - name: run Lighthouse CI
      id: lighthouse
      run: |
          npm install -g @lhci/cli@0.13.x
          lhci autorun \
          --config=./lighthouserc.json
      env:
            LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
    
    - name: Debug Lighthouse Output
      if: ${{ success() }}
      run: |
        echo "Lighthouse output manifest:"
        echo "${{ steps.lighthouse.outputs }}"
