name: Lighthouse CI

on: [workflow_dispatch, pull_request]

jobs:
  lighthouse:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2

    - name: yarn install, build
      run: |
          yarn install
          yarn run build

    - name: Run Lighthouse CI, Extract & Apply Url To Step Summary
      id: lighthouse
      run: |
        npm install -g @lhci/cli@0.13.x
        LHCI_OUTPUT=$(lhci autorun --config=./lighthouse/lighthouserc.yml | grep '.html' | awk '{print $NF}')
        echo "### Lighthouse CI Report URL:" >> $GITHUB_STEP_SUMMARY
        echo "$LHCI_OUTPUT" >> $GITHUB_STEP_SUMMARY
        
    - name: Convert JSON to Markdown and Add to Job Summary
      run: |
        node ./lighthouse/lighthouseResultsToMarkdown.js >> $GITHUB_STEP_SUMMARY

    - name: Archive Lighthouse Results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: lighthouse-results
        path: lighthouseci/*
