name: Trigger Lighthouse CI

on:
  workflow_dispatch:
    inputs:
      working-directory:
        description: "Working Directory for the Lighthouse CI"
        required: false
        type: string
      node-version:
        description: "Node.js Version"
        required: false
        type: string
      build-script:
        description: "Build script command"
        required: false
        type: string
      lhci-version:
        description: "Lighthouse CI CLI Version"
        required: false
        type: string
      lighthouserc-path:
        description: "Path to lighthouserc.yml"
        required: true
        type: string

jobs:
  lighthouse-ci:
    name: 🌟 Lighthouse CI Audit
    uses: dpbeaumont/ligthouse-ci/.github/workflows/lighthouse-ci.yml@main
    with:
      working-directory: ${{ github.event.inputs.working-directory }}
      node-version: ${{ github.event.inputs.node-version }}
      build-script: ${{ github.event.inputs.build-script }}
      lhci-version: ${{ github.event.inputs.lhci-version }}
      lighthouserc-path: ${{ github.event.inputs.lighthouserc-path }}
