name: Lighthouse CI

on: [workflow_dispatch]

jobs:
  lighthouse:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '18.17.0'

    - name: Install dependencies
      run: yarn install

    - name: Build Next.js Application
      run: yarn build

    - name: run Lighthouse CI
      run: |
          npm install -g @lhci/cli@0.13.x
          lhci autorun
