name: Lighthouse CI

on: [workflow_dispatch, pull_request]

jobs:
  lighthouse:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2

    - name: yarn install, build
      run: |
          yarn install
          yarn run build

    - name: run Lighthouse CI
      id: lighthouse
      run: |
        npm install -g @lhci/cli@0.13.x
        output=$(lhci autorun --config=./lighthouserc.json)
        echo "$output"
        echo "::set-output name=lighthouseOutput::$output"

    - name: List contents of .lighthouseci directory
      if: ${{ success() }}
      run: |
        echo "Listing contents of .lighthouseci directory:"
        ls -la .lighthouseci/
        
    - name: Display contents of assertion-results.json
      run: cat .lighthouseci/assertion-results.json
    
    - name: Debug Lighthouse Output
      if: ${{ success() }}
      run: |
        echo "Lighthouse output:"
        echo "${{ steps.lighthouse.outputs.lighthouseOutput }}"
