name: Lighthouse CI

on: [workflow_dispatch, pull_request]

jobs:
  lighthouse:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2

    - name: yarn install, build
      run: |
          yarn install
          yarn run build

    - name: run Lighthouse CI
      id: lighthouse
      run: |
        npm install -g @lhci/cli@0.13.x
        LHCI_OUTPUT=$(lhci autorun --config=./lighthouserc.json | grep 'storage.googleapis.com')
        echo "Captured Lighthouse CI Output:"
        echo "$LHCI_OUTPUT"
        
    - name: Display contents of assertion-results.json
      run: cat .lighthouseci/assertion-results.json

    - name: Convert JSON to Markdown and Add to Job Summary
      run: |
        node lighthouseResultsToMarkdown.js >> $GITHUB_STEP_SUMMARY

    - name: Upload Markdown Results
      uses: actions/upload-artifact@v2
      with:
        name: markdown-results
        path: assertion-results.md
